### ISSUE TITLE
打开网页全是404

### ISSUE THREAD

**Issue by voguke** [km1994/nlp_paper_study#1]
打扰您了，之前看到您总结了这么多知识非常开心，不过我在点进去具体网页的时候却都是404，这是怎么回事呢？

**Comment by km1994** [comment]
建议clone 到，本地，我的文件路径有时候会做了一下修改，导致 md 忘记调整过来，但是 md 上面有的东西，基本都存在把

**Comment by JiaxiangBU** [comment]
https://github.com/km1994/nlp_paper_study/tree/master/ACL2020_bertpaper_CHECKLIST/ 这个链接也 404 了。

**Comment by km1994** [comment]
修改好了，链接为 https://github.com/km1994/nlp_paper_study/tree/master/other_study/meeting/ACL_study/ACL2020_bertpaper_CHECKLIST/

**Comment by kuangxiong** [comment]
作者您好，之前发现您写的一些总结，很受益，但是忘记clone到本地了，现在这个网址 https://github.com/km1994/NLP-Interview-Notes 带不开了，怎样才能获取这些内容呢？谢谢

**Comment by km1994** [comment]
> 作者您好，之前发现您写的一些总结，很受益，但是忘记clone到本地了，现在这个网址 https://github.com/km1994/NLP-Interview-Notes 带不开了，怎样才能获取这些内容呢？谢谢

你好，很感谢你的认可，但是该项目在复查之后，发现蛮多理解错误性的问题，所以我把项目关了，后期检查没问题了再公开，到时公开了，会联系你的

**Comment by balataTree** [comment]
https://github.com/km1994/NLP-Interview-Notes 期待这个网址再次复活

**Comment by pppihf** [comment]
https://github.com/km1994/NLP-Interview-Notes 期待这个网址再次复活
