### ISSUE TITLE
星球有优惠码吗？

### ISSUE THREAD

**Issue by charmby** [km1994/nlp_paper_study#10]
星球有优惠码吗？

**Comment by km1994** [comment]
有，可以加微信 blqkm601 聊

**Comment by km1994** [comment]
知识星球 团购优惠价:  [https://mp.weixin.qq.com/s/Zvtx4KUGl4ukrWan1qGaOw](https://mp.weixin.qq.com/s/Zvtx4KUGl4ukrWan1qGaOw)
