### ISSUE TITLE
关于 https://github.com/km1994/NLP-Interview-Notes 项目 打不开问题

### ISSUE THREAD

**Issue by km1994** [km1994/nlp_paper_study#2]
《关于 https://github.com/km1994/NLP-Interview-Notes 项目 打不开问题》

大家好，很感谢大家对这个项目的支持，这个项目是我过去半年和小伙伴一起写的一个 NLP 小面筋，但是这段时间，我重新去review 的时候，发现很多地方存在我理解错误的问题，为了防止误导大家，我先把项目关了，并已经开始花时间去 重新纠正 该项目的错误。如果由于该项目问题给大家带了不便，我在这里表示很抱歉，也会抓紧时间把他改好并开源，并希望他能帮助到更多的 NLPer。

**Comment by IchijikuJP** [comment]
repost

**Comment by km1994** [comment]
https://github.com/km1994/NLP-Interview-Notes 项目 项目已可以使用，欢迎一起学习。
