### ISSUE TITLE
Sentence-BERT

### ISSUE THREAD

**Issue by LiuChen19960902** [km1994/nlp_paper_study#3]
大佬，Sentence-BERT项目下为啥是SimCSE，不应该是SBERT嘛

**Comment by km1994** [comment]
谢谢大佬提醒，已经修正

**Comment by LiuChen19960902** [comment]
哈喽，我又来啦～
想请教一下关于SBERT的计算时间问题，在1.1.3问题分析中，SBERT先对每个句子进行一次离线的embedding计算，然后存下来，这一步我理解。但是后面关于“在计算相似的时候，只需要将句子的 embedding 输入到模型中两两之间计算cosine similarity就可以”，将句子的embedding输入到模型中，不还是要用BERT进行一次inference嘛，这样不就仍然是BERT+Cos sim。

**Comment by km1994** [comment]
为什么需要呢？SBert embedding 一次就好了，后面只需要 Cos 就好了，Bert 因为每次计算相似度都需要 把两个句子拼接，所以 需要重新 embedding
